
services:
  db:
    image: leogloriainfnet/postgres-tp2-spring:2.0-win
    ports:
      - "5432:5432"
    container_name: TP2_SpringBoot
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
  elastic:
    image: leogloriainfnet/elastic-tp2-spring:1.0-windows
    ports:
      - "9200:9200"
    container_name: guilda-es
    restart: always
    environment:
      - discovery.type=single-node  #sobe como um nó só, sem cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m #controle de memória
      - ELASTIC_PASSWORD=123
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s #elastic demora pra subir
volumes:
  pgdata: